import { randomInt, randomUUID, timingSafeEqual } from 'node:crypto';
import { clueDeck, meansDeck, sceneDeck, type Card, type Phase, type Role, type Scene, type View } from '../../shared/deception.js';
type Player = {id:string;token:string;socketId:string|null;name:string;ready:boolean;role:Role;confirmed:boolean;means:Card[];clues:Card[];attempted:boolean;departed?:boolean};
export type Room = {code:string;name:string;capacity:number;hostId:string;phase:Phase;round:number;players:Player[];scene:Scene[];solution:{murdererId:string;meansId:string;clueId:string}|null;forensicReady:boolean;log:{name:string;round:number;correct:boolean}[];lastActive:number};
export class DeceptionManager {
  rooms=new Map<string,Room>();
  constructor(private rng:(max:number)=>number=randomInt){}
  private txt(value:unknown,max:number){if(typeof value!=='string'||!value.trim()||value.trim().length>max)throw Error('กรอกข้อมูลให้ถูกต้อง');return value.trim();}
  private player(socketId:string,name:string):Player{return{id:randomUUID(),token:randomUUID(),socketId,name,ready:false,role:'investigator',confirmed:false,means:[],clues:[],attempted:false};}
  private free(socketId:string){for(const r of this.rooms.values())if(r.players.some(p=>p.socketId===socketId))throw Error('คุณอยู่ในห้องแล้ว');}
  auth(socketId:string){for(const room of this.rooms.values()){const player=room.players.find(p=>p.socketId===socketId);if(player)return {room,player};}throw Error('กรุณาเข้าห้องก่อน');}
  credentials(room:Room,p:Player){return{code:room.code,id:p.id,token:p.token};}
  create(socketId:string,data:Record<string,unknown>){this.free(socketId);const name=this.txt(data.playerName,24),roomName=this.txt(data.roomName,40);if(!Number.isInteger(data.capacity)||Number(data.capacity)<4||Number(data.capacity)>8)throw Error('ห้องรองรับ 4–8 คน');let code='';do{code=String(randomInt(100000,1000000));}while(this.rooms.has(code));const p=this.player(socketId,name);const room:Room={code,name:roomName,capacity:Number(data.capacity),hostId:p.id,phase:'lobby',round:0,players:[p],scene:[],solution:null,forensicReady:false,log:[],lastActive:Date.now()};this.rooms.set(code,room);return{room,player:p};}
  join(socketId:string,data:Record<string,unknown>){this.free(socketId);const room=this.rooms.get(this.txt(data.code,6));if(!room)throw Error('ไม่พบห้อง');if(room.phase!=='lobby')throw Error('เกมเริ่มแล้ว');if(room.players.length>=room.capacity)throw Error('ห้องเต็ม');const name=this.txt(data.playerName,24);if(room.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))throw Error('ชื่อนี้มีคนใช้แล้ว');const player=this.player(socketId,name);room.players.push(player);room.lastActive=Date.now();return{room,player};}
  rejoin(socketId:string,data:Record<string,unknown>){this.free(socketId);const room=this.rooms.get(String(data.code));const player=room?.players.find(p=>p.id===data.id);if(!room||!player||typeof data.token!=='string'||Buffer.byteLength(data.token)!==Buffer.byteLength(player.token)||!timingSafeEqual(Buffer.from(data.token),Buffer.from(player.token)))throw Error('คืนที่นั่งไม่ได้');if(player.socketId)throw Error('ที่นั่งนี้เปิดอยู่ในเครื่องอื่น');player.socketId=socketId;if(!room.players.some(p=>p.id===room.hostId&&p.socketId))room.hostId=player.id;room.lastActive=Date.now();return{room,player};}
  paused(room:Room){return room.phase!=='lobby'&&room.phase!=='result'&&room.players.some(p=>!p.socketId);}
  disconnect(socketId:string){let found;try{found=this.auth(socketId);}catch{return null;}const{room,player}=found;player.socketId=null;if(room.hostId===player.id)room.hostId=room.players.find(p=>p.socketId)?.id??player.id;room.lastActive=Date.now();return room;}
  leave(socketId:string){const{room,player}=this.auth(socketId);if(room.phase!=='lobby'&&room.phase!=='result')throw Error('รอเกมจบก่อนออกจากห้อง');if(room.phase==='result'){player.socketId=null;player.departed=true;player.token=randomUUID();}else room.players=room.players.filter(p=>p!==player);if(room.hostId===player.id)room.hostId=room.players.find(p=>p.socketId)?.id??room.players[0]?.id??'';if(!room.players.length||room.players.every(p=>p.departed))this.rooms.delete(room.code);return room;}
  private draw(deck:string[],count:number,prefix:string,used:Set<number>){const cards:Card[]=[];while(cards.length<count){const idx=this.rng(deck.length);if(used.has(idx))continue;used.add(idx);cards.push({id:`${prefix}${idx}`,name:deck[idx]});}return cards;}
  private fresh(room:Room){const usedMeans=new Set<number>(),usedClues=new Set<number>();const forensic=this.rng(room.players.length), murderer=(forensic+1+this.rng(room.players.length-1))%room.players.length;for(const[pIndex,p]of room.players.entries()){p.role=pIndex===forensic?'forensic':pIndex===murderer?'murderer':'investigator';p.ready=false;p.confirmed=false;p.attempted=false;p.means=p.role==='forensic'?[]:this.draw(meansDeck,4,'m',usedMeans);p.clues=p.role==='forensic'?[]:this.draw(clueDeck,4,'c',usedClues);}const special=sceneDeck.slice(0,2);const used=new Set<number>([0,1]);const extra=this.draw(sceneDeck.map(x=>x.title),4,'s',used).map(c=>sceneDeck[Number(c.id.slice(1))]);room.scene=[...special,...extra].map(x=>({...x,chosen:null}));room.solution=null;room.forensicReady=false;room.log=[];room.round=1;room.phase='reveal';}
  action(socketId:string,event:string,data:Record<string,unknown>={}){const{room,player:p}=this.auth(socketId);const phase=(x:Phase)=>{if(room.phase!==x)throw Error('ขั้นตอนนี้ยังไม่พร้อม');};const host=()=>{if(room.hostId!==p.id)throw Error('เฉพาะเจ้าของห้อง')};const forensic=()=>{if(p.role!=='forensic')throw Error('เฉพาะนิติเวช')};if(this.paused(room))throw Error('รอผู้เล่นที่หลุดกลับเข้าห้อง');switch(event){
    case 'ready':phase('lobby');p.ready=!p.ready;break;
    case 'start':host();phase('lobby');if(room.players.length<4||room.players.some(q=>!q.ready||!q.socketId))throw Error('ต้องมีอย่างน้อย 4 คนและทุกคนพร้อม');this.fresh(room);break;
    case 'confirm':phase('reveal');p.confirmed=true;if(room.players.every(q=>q.confirmed))room.phase='crime';break;
    case 'select_crime':{phase('crime');if(p.role!=='murderer')throw Error('เฉพาะฆาตกร');const meansId=String(data.meansId),clueId=String(data.clueId);if(!p.means.some(c=>c.id===meansId)||!p.clues.some(c=>c.id===clueId))throw Error('เลือกจากการ์ดของคุณอย่างละหนึ่งใบ');room.solution={murdererId:p.id,meansId,clueId};room.phase='forensic';break;}
    case 'mark':{phase('forensic');forensic();const scene=room.scene.find(x=>x.id===data.sceneId);const option=data.option;if(!scene||!Number.isInteger(option)||Number(option)<0||Number(option)>=scene.options.length)throw Error('เลือกคำใบ้ที่ถูกต้อง');if(room.round>1&&room.forensicReady&&scene.chosen!==null)throw Error('รอบนี้เปลี่ยนคำใบ้ใหม่ได้เพียงหนึ่งช่อง');scene.chosen=Number(option);room.forensicReady=room.scene.every(x=>x.chosen!==null);break;}
    case 'open_discussion':phase('forensic');forensic();if(!room.forensicReady)throw Error('นิติเวชต้องให้คำใบ้ครบก่อน');room.phase='investigation';break;
    case 'accuse':{phase('investigation');if(p.role==='forensic'||p.attempted)throw Error('คุณใช้สิทธิ์กล่าวหาแล้ว');const murderer=room.players.find(q=>q.id===data.murdererId);if(!murderer||!murderer.means.some(c=>c.id===data.meansId)||!murderer.clues.some(c=>c.id===data.clueId))throw Error('ต้องเลือกผู้ต้องสงสัย อาวุธและหลักฐานจากการ์ดของคนนั้น');p.attempted=true;const correct=!!room.solution&&room.solution.murdererId===murderer.id&&room.solution.meansId===data.meansId&&room.solution.clueId===data.clueId;room.log.push({name:p.name,round:room.round,correct});if(correct)room.phase='result';break;}
    case 'next_round':phase('investigation');forensic();if(room.round===3)throw Error('ครบสามรอบแล้ว กรุณาจบคดี');room.round++;room.phase='forensic';room.forensicReady=false;{const used=new Set(room.scene.map(x=>sceneDeck.findIndex(y=>y.id===x.id)));const card=this.draw(sceneDeck.map(x=>x.title),1,'s',used)[0];const replace=room.scene.findIndex(x=>x.id===data.replaceId&&x.id!=='cause'&&x.id!=='location');if(replace<0)throw Error('เลือกช่องคำใบ้ที่ต้องการเปลี่ยน');room.scene[replace]={...sceneDeck[Number(card.id.slice(1))],chosen:null};}break;
    case 'finish':phase('investigation');forensic();if(room.round!==3)throw Error('คดีจบหลังอภิปรายครบสามรอบ');room.phase='result';break;
    case 'restart':phase('result');host();room.players=room.players.filter(q=>!q.departed);room.phase='lobby';room.round=0;room.solution=null;room.scene=[];room.log=[];room.players.forEach(q=>{q.ready=false;q.confirmed=false;q.attempted=false;q.means=[];q.clues=[];});break;
    case 'remove':phase('lobby');host();{const target=room.players.find(q=>q.id===data.targetId);if(!target||target.socketId)throw Error('นำออกได้เฉพาะผู้ที่หลุด');room.players=room.players.filter(q=>q!==target);}break;
    default:throw Error('ไม่รู้จักคำสั่ง');
  }room.lastActive=Date.now();return room;}
  snapshot(room:Room,p:Player):View{const solution=room.solution;return {code:room.code,name:room.name,capacity:room.capacity,hostId:room.hostId,phase:room.phase,round:room.round,paused:this.paused(room),players:room.players.map(q=>({id:q.id,name:q.name,connected:!!q.socketId,ready:q.ready,means:q.means,clues:q.clues,attempted:q.attempted})),scene:room.scene,forensicReady:room.forensicReady,me:{id:p.id,role:room.phase==='lobby'?null:p.role,confirmed:p.confirmed,solution:(p.role==='forensic'||p.role==='murderer'||room.phase==='result')?solution:null},result:room.phase==='result'&&solution?{winner:room.log.some(x=>x.correct)?'investigators':'murderer',...solution}:null,log:room.log};}
}
