import { randomInt, randomUUID, timingSafeEqual } from 'node:crypto';
import { castFor, evidence, roleInfo, type Evidence, type Phase, type Role, type View, type VoteSummary } from '../../shared/dying.js';

type Player = { id:string; token:string; socketId:string|null; name:string; ready:boolean; role:Role; confirmed:boolean; alive:boolean; vote:string|null; departed?:boolean };
export type Room = { code:string; name:string; capacity:number; hostId:string; players:Player[]; phase:Phase; round:number; victimId:string|null; protectedId:string|null; choices:Evidence[]; realIds:number[]; fakeIds:number[]; summary:VoteSummary|null; winner:'innocents'|'murderer'|null; lastActive:number };

export class DyingManager {
  rooms = new Map<string,Room>();
  constructor(private rng:(max:number)=>number=randomInt) {}
  private text(value:unknown,max:number) { if(typeof value!=='string'||!value.trim()||value.trim().length>max)throw Error('กรอกข้อมูลให้ถูกต้อง');return value.trim(); }
  private free(socketId:string) { for(const room of this.rooms.values())if(room.players.some(p=>p.socketId===socketId))throw Error('คุณอยู่ในห้องแล้ว'); }
  private player(socketId:string,name:string):Player { return {id:randomUUID(),token:randomUUID(),socketId,name,ready:false,role:'innocent',confirmed:false,alive:true,vote:null}; }
  private killer(room:Room) { return room.players.find(p=>roleInfo[p.role].team==='murderer')!; }
  private realCount(room:Room) { return room.players.find(p=>p.id===room.victimId)?.role==='noble'?2:1; }
  private fakeCount(room:Room) { return (this.killer(room).role==='professional'?3:2)-(room.players.find(p=>p.id===room.victimId)?.role==='celebrity'?1:0); }
  auth(socketId:string) { for(const room of this.rooms.values()){const player=room.players.find(p=>p.socketId===socketId);if(player)return{room,player};}throw Error('กรุณาเข้าห้องก่อน'); }
  credentials(room:Room,p:Player) { return {code:room.code,id:p.id,token:p.token}; }
  create(socketId:string,data:Record<string,unknown>) { this.free(socketId);const name=this.text(data.playerName,24),roomName=this.text(data.roomName,40);if(!Number.isInteger(data.capacity)||Number(data.capacity)<4||Number(data.capacity)>8)throw Error('ห้องรองรับ 4–8 คน');let code:string;do{code=String(randomInt(100000,1000000));}while(this.rooms.has(code));const player=this.player(socketId,name);const room:Room={code,name:roomName,capacity:Number(data.capacity),hostId:player.id,players:[player],phase:'lobby',round:0,victimId:null,protectedId:null,choices:[],realIds:[],fakeIds:[],summary:null,winner:null,lastActive:Date.now()};this.rooms.set(code,room);return{room,player}; }
  join(socketId:string,data:Record<string,unknown>) { this.free(socketId);const room=this.rooms.get(this.text(data.code,6));if(!room)throw Error('ไม่พบห้อง');if(room.phase!=='lobby')throw Error('เกมเริ่มแล้ว');if(room.players.length>=room.capacity)throw Error('ห้องเต็มแล้ว');const name=this.text(data.playerName,24);if(room.players.some(p=>p.name.toLocaleLowerCase()===name.toLocaleLowerCase()))throw Error('ชื่อนี้มีคนใช้แล้ว');const player=this.player(socketId,name);room.players.push(player);room.lastActive=Date.now();return{room,player}; }
  rejoin(socketId:string,data:Record<string,unknown>) { this.free(socketId);const room=this.rooms.get(String(data.code)),player=room?.players.find(p=>p.id===data.id);if(!room||!player||typeof data.token!=='string'||Buffer.byteLength(data.token)!==Buffer.byteLength(player.token)||!timingSafeEqual(Buffer.from(data.token),Buffer.from(player.token)))throw Error('คืนที่นั่งไม่ได้');if(player.socketId)throw Error('ที่นั่งนี้เปิดอยู่ในเครื่องอื่น');player.socketId=socketId;if(!room.players.some(p=>p.id===room.hostId&&p.socketId))room.hostId=player.id;room.lastActive=Date.now();return{room,player}; }
  paused(room:Room) { return room.phase!=='lobby'&&room.phase!=='result'&&room.players.some(p=>!p.socketId&&(p.alive||room.phase==='real_clue'&&p.id===room.victimId)); }
  disconnect(socketId:string) { let found;try{found=this.auth(socketId);}catch{return null;}const{room,player}=found;player.socketId=null;if(room.hostId===player.id)room.hostId=room.players.find(p=>p.socketId)?.id??player.id;room.lastActive=Date.now();return room; }
  leave(socketId:string) { const{room,player}=this.auth(socketId);if(!['lobby','result'].includes(room.phase))throw Error('ระหว่างเกมต้องรอจนจบรอบก่อนออกจากห้อง');if(room.phase==='result'){player.socketId=null;player.departed=true;player.token=randomUUID();}else room.players=room.players.filter(p=>p!==player);if(room.hostId===player.id)room.hostId=room.players.find(p=>p.socketId)?.id??room.players[0]?.id??'';if(!room.players.length||room.players.every(p=>p.departed))this.rooms.delete(room.code);return room; }
  private choices() { const pool=[...evidence];for(let i=pool.length-1;i>0;i--){const j=this.rng(i+1);[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,9); }
  private startRound(room:Room) { room.round++;room.victimId=null;room.protectedId=null;room.choices=this.choices();room.realIds=[];room.fakeIds=[];room.summary=null;room.players.forEach(p=>p.vote=null);room.phase=room.players.some(p=>p.role==='guard'&&p.alive)?'guard':'kill'; }
  private finishVote(room:Room) { const alive=room.players.filter(p=>p.alive),counts=alive.map(p=>({id:p.id,count:alive.filter(q=>q.vote===p.id).length})),max=Math.max(...counts.map(x=>x.count)),leaders=counts.filter(x=>x.count===max),accusedId=leaders.length===1?leaders[0].id:null,caught=accusedId===this.killer(room).id;room.summary={accusedId,tied:!accusedId,counts,caught};if(accusedId)room.players.find(p=>p.id===accusedId)!.alive=false;if(caught){room.winner='innocents';room.phase='result';}else if(!room.players.some(p=>p.alive&&roleInfo[p.role].team==='innocents')){room.winner='murderer';room.phase='result';}else room.phase='round_end'; }
  action(socketId:string,event:string,data:Record<string,unknown>={}) {
    const{room,player:p}=this.auth(socketId),phase=(name:Phase)=>{if(room.phase!==name)throw Error('ยังไม่ใช่ขั้นตอนนี้');},host=()=>{if(room.hostId!==p.id)throw Error('เฉพาะเจ้าของห้อง');},killer=()=>{if(roleInfo[p.role].team!=='murderer'||!p.alive)throw Error('เฉพาะฆาตกรที่ยังอยู่');};
    if(this.paused(room))throw Error('รอผู้เล่นที่หลุดกลับเข้าห้อง');
    switch(event) {
      case 'ready':phase('lobby');p.ready=!p.ready;break;
      case 'start':host();phase('lobby');if(room.players.length<4||room.players.some(q=>!q.ready||!q.socketId))throw Error('ต้องมีอย่างน้อย 4 คนและทุกคนพร้อม');{const cast=castFor(room.players.length);for(let i=cast.length-1;i>0;i--){const j=this.rng(i+1);[cast[i],cast[j]]=[cast[j],cast[i]];}room.players.forEach((q,i)=>{q.role=cast[i];q.alive=true;q.confirmed=false;q.vote=null;q.ready=false;});room.round=0;room.winner=null;room.phase='reveal';}break;
      case 'confirm':phase('reveal');p.confirmed=true;if(room.players.every(q=>q.confirmed))this.startRound(room);break;
      case 'protect':phase('guard');if(p.role!=='guard'||!p.alive)throw Error('เฉพาะสุนัขเฝ้ายาม');{const target=room.players.find(q=>q.id===data.targetId&&q.alive&&q!==p);if(!target)throw Error('เลือกผู้เล่นอื่นที่ยังอยู่');room.protectedId=target.id;room.phase='kill';}break;
      case 'kill':phase('kill');killer();{const target=room.players.find(q=>q.id===data.targetId&&q.alive&&q!==p);if(!target)throw Error('เลือกผู้เล่นอื่นที่ยังอยู่');if(target.id===room.protectedId)throw Error('เป้าหมายถูกปกป้อง เลือกคนอื่น');target.alive=false;room.victimId=target.id;if(!room.players.some(q=>q.alive&&roleInfo[q.role].team==='innocents')){room.winner='murderer';room.phase='result';}else room.phase='real_clue';}break;
      case 'real_clue':phase('real_clue');if(p.id!==room.victimId)throw Error('เฉพาะเหยื่อ');{const ids=data.clueIds??(data.clueId===undefined?null:[data.clueId]);if(!Array.isArray(ids)||ids.length!==this.realCount(room)||new Set(ids).size!==ids.length||ids.some(id=>!Number.isInteger(id)||!room.choices.some(c=>c.id===id)))throw Error(`เลือกเบาะแสจริง ${this.realCount(room)} ใบ`);room.realIds=ids as number[];room.phase=room.players.some(q=>q.role==='detective'&&q.alive)?'detective':'fake_clues';}break;
      case 'ack_detective':phase('detective');if(p.role!=='detective'||!p.alive)throw Error('เฉพาะนักสืบที่ยังอยู่');room.phase='fake_clues';break;
      case 'fake_clues':phase('fake_clues');killer();{const ids=data.clueIds;if(!Array.isArray(ids)||ids.length!==this.fakeCount(room)||new Set(ids).size!==ids.length||ids.some(id=>!Number.isInteger(id)||room.realIds.includes(id)||!room.choices.some(c=>c.id===id)))throw Error(`เลือกเบาะแสลวง ${this.fakeCount(room)} ใบที่ไม่ซ้ำของจริง`);room.fakeIds=ids as number[];room.phase='discussion';}break;
      case 'open_vote':phase('discussion');host();room.phase='vote';break;
      case 'vote':phase('vote');if(!p.alive||p.vote!==null)throw Error('คุณไม่มีสิทธิ์โหวตในรอบนี้');if(!room.players.some(q=>q.id===data.targetId&&q.alive))throw Error('เลือกผู้เล่นที่ยังอยู่');p.vote=String(data.targetId);if(room.players.filter(q=>q.alive).every(q=>q.vote!==null))this.finishVote(room);break;
      case 'next_round':phase('round_end');host();this.startRound(room);break;
      case 'restart':phase('result');host();room.players=room.players.filter(q=>!q.departed);room.phase='lobby';room.round=0;room.victimId=null;room.protectedId=null;room.choices=[];room.realIds=[];room.fakeIds=[];room.summary=null;room.winner=null;room.players.forEach(q=>{q.ready=false;q.confirmed=false;q.alive=true;q.vote=null;q.role='innocent';});break;
      case 'remove':phase('lobby');host();{const q=room.players.find(x=>x.id===data.targetId);if(!q||q.socketId)throw Error('นำออกได้เฉพาะผู้ที่หลุด');room.players=room.players.filter(x=>x!==q);}break;
      default:throw Error('ไม่รู้จักคำสั่ง');
    }
    room.lastActive=Date.now();return room;
  }
  snapshot(room:Room,p:Player):View {
    const reveal=['discussion','vote','round_end','result'].includes(room.phase),picked=[...room.realIds,...room.fakeIds],isKiller=roleInfo[p.role].team==='murderer',isVictim=room.victimId===p.id;
    return {code:room.code,name:room.name,capacity:room.capacity,hostId:room.hostId,phase:room.phase,round:room.round,paused:this.paused(room),players:room.players.map(q=>({id:q.id,name:q.name,connected:!!q.socketId,ready:q.ready,alive:q.alive})),victimId:room.victimId,clueChoices:isVictim&&room.phase==='real_clue'||isKiller&&room.phase==='fake_clues'?room.choices:[],revealedClues:reveal?room.choices.filter(c=>picked.includes(c.id)):[],realClueCount:room.victimId?this.realCount(room):1,fakeClueCount:room.victimId?this.fakeCount(room):isKiller&&p.role==='professional'?3:2,voteCount:room.players.filter(q=>q.vote!==null).length,me:{id:p.id,role:room.phase==='lobby'?null:p.role,confirmed:p.confirmed,alive:p.alive,isVictim,secretMurdererId:isKiller||isVictim||room.phase==='result'?this.killer(room).id:null,realClueIds:isKiller&&room.phase==='fake_clues'||p.role==='detective'&&room.phase==='detective'&&p.alive?room.realIds:[],protectedId:p.role==='guard'?room.protectedId:null,hasVoted:p.vote!==null},summary:room.phase==='round_end'||room.phase==='result'?room.summary:null,winner:room.phase==='result'?room.winner:null,murdererId:room.phase==='result'?this.killer(room).id:null};
  }
}
